import mongoose from 'mongoose';
import { Subject, Cronograma } from './models/subject.js';
const userMongoDB = "plannerpsy1518"
const passwordMongoDB = "psy1518"
const databaseMongoDB = "plannerDB"

const uri = `mongodb+srv://${userMongoDB}:${passwordMongoDB}@cluster0.w4fuw.mongodb.net/${databaseMongoDB}?retryWrites=true&w=majority`

async function populateDatabase() {
    try {
        await mongoose.connect(uri);
        console.log('🔥 Conectado ao MongoDB');

        await Subject.insertMany([
            /*{
              subject: "Biologia",
              topics: [
                { assunto: "Organização dos Seres Vivos e Bioenergética", volume: 1, frente: 1, pinicial: 6, pfinal: 9, prop: 13, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Evolução: conceitos e evidências", volume: 1, frente: 2, pinicial: 88, pfinal: 95, prop: 99, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Classificação dos Seres Vivos e Introdução à Biologia", volume: 1, frente: 3, pinicial: 200, pfinal: 205, prop: 210, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Noções de material genético e núcleo", volume: 1, frente: 1, pinicial: 22, pfinal: 26, prop: 28, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Evolução", volume: 1, frente: 2, pinicial: 114, pfinal: 117, prop: 119, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Fundamentos da Ecologia", volume: 1, frente: 2, pinicial: 130, pfinal: 132, prop: 134, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Protozoários e protozooses", volume: 1, frente: 3, pinicial: 228, pfinal: 231, prop: 237, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Divisão Celular: Mitose e meiose", volume: 1, frente: 1, pinicial: 36, pfinal: 42, prop: 47, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "A geração de vida e o Método Científico", volume: 1, frente: 1, pinicial: 62, pfinal: 64, prop: 65, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Energia e matéria no ecossistema", volume: 1, frente: 2, pinicial: 142, pfinal: 144, prop: 150, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Embriologia dos animais", volume: 1, frente: 3, pinicial: 256, pfinal: 261, prop: 264, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Composição Química dos Seres Vivos", volume: 1, frente: 1, pinicial: 72, pfinal: 75, prop: 79, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Populações, comunidades e sucessão ecológica", volume: 1, frente: 2, pinicial: 168, pfinal: 175, prop: 179, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Zoologia dos invertebrados 1", volume: 1, frente: 3, pinicial: 278, pfinal: 289, prop: 294, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Proteínas", volume: 2, frente: 1, pinicial: 6, pfinal: 11, prop: 13, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Ácidos nucleicos e síntese de proteínas", volume: 2, frente: 1, pinicial: 20, pfinal: 26, prop: 28, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "O ser humano e o ambiente", volume: 2, frente: 2, pinicial: 118, pfinal: 130, prop: 135, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Zoologia dos invertebrados 2", volume: 2, frente: 3, pinicial: 248, pfinal: 264, prop: 266, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Bioenergética", volume: 2, frente: 1, pinicial: 44, pfinal: 51, prop: 54, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Procariontes: bactérias e arqueas", volume: 2, frente: 2, pinicial: 160, pfinal: 163, prop: 164, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Vírus", volume: 2, frente: 2, pinicial: 178, pfinal: 182, prop: 184, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Fungos e algas", volume: 2, frente: 2, pinicial: 198, pfinal: 202, prop: 204, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Zoologia dos vertebrados", volume: 2, frente: 3, pinicial: 294, pfinal: 308, prop: 311, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Origem dos primeiros seres vivos", volume: 2, frente: 1, pinicial: 76, pfinal: 77, prop: 79, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Citoplasma e hipótese da endossibiose", volume: 2, frente: 1, pinicial: 90, pfinal: 94, prop: 96, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Plantas e ciclos reprodutivos", volume: 2, frente: 2, pinicial: 216, pfinal: 216, prop: 218, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Digestão e respiração", volume: 2, frente: 3, pinicial: 332, pfinal: 340, prop: 343, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Os envoltórios celulares", volume: 2, frente: 1, pinicial: 110, pfinal: 111, prop: 112, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Briófitas e pteridófitas", volume: 2, frente: 2, pinicial: 224, pfinal: 226, prop: 228, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Gimnospermas", volume: 2, frente: 2, pinicial: 238, pfinal: 239, prop: 241, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "O transporte através da membrana", volume: 3, frente: 1, pinicial: 6, pfinal: 9, prop: 10, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Angiospermas", volume: 3, frente: 2, pinicial: 66, pfinal: 74, prop: 77, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Circulação e imunidade", volume: 3, frente: 3, pinicial: 150, pfinal: 165, prop: 166, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Introdução à Genética clássica", volume: 3, frente: 1, pinicial: 18, pfinal: 24, prop: 25, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Morfologia externa das plantas", volume: 3, frente: 2, pinicial: 88, pfinal: 109, prop: 94, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Tecidos vegetais", volume: 3, frente: 2, pinicial: 104, pfinal: 106, prop: 107, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Excreção e sistema urinário", volume: 3, frente: 3, pinicial: 190, pfinal: 194, prop: 196, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "As variações da primeira lei de Mendel", volume: 3, frente: 1, pinicial: 36, pfinal: 38, prop: 39, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Nutrição e secreção vegetal", volume: 3, frente: 2, pinicial: 114, pfinal: 118, prop: 120, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Sistemas de controle I", volume: 3, frente: 3, pinicial: 212, pfinal: 222, prop: 224, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Alelos múltiplos", volume: 3, frente: 1, pinicial: 46, pfinal: 50, prop: 52, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Revestimentos e trocas gasosas", volume: 3, frente: 2, pinicial: 132, pfinal: 136, prop: 137, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Sistemas de controle II", volume: 4, frente: 3, pinicial: 172, pfinal: 178, prop: 179, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Segunda Lei de Mendel", volume: 4, frente: 1, pinicial: 6, pfinal: 8, prop: 9, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Interações gênicas", volume: 4, frente: 1, pinicial: 20, pfinal: 24, prop: 26, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Linkage e mapas gênicos", volume: 4, frente: 1, pinicial: 36, pfinal: 39, prop: 41, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Genoma humano e cromossomos sexuais", volume: 4, frente: 1, pinicial: 50, pfinal: 54, prop: 56, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Mutações gênicas e cromossômicas", volume: 4, frente: 1, pinicial: 70, pfinal: 73, prop: 74, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Genética das populações", volume: 4, frente: 1, pinicial: 84, pfinal: 86, prop: 87, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Transporte e sustentação em plantas", volume: 4, frente: 2, pinicial: 96, pfinal: 101, prop: 103, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Hormônios vegetais", volume: 4, frente: 2, pinicial: 114, pfinal: 117, prop: 119, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Movimentos vegetais e fotoperiodismo", volume: 4, frente: 2, pinicial: 130, pfinal: 134, prop: 136, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Plantas e ambiente", volume: 4, frente: 2, pinicial: 144, pfinal: 154, prop: 157, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Sistemas de controle II", volume: 4, frente: 3, pinicial: 172, pfinal: 178, prop: 179, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Reprodução Humana", volume: 4, frente: 3, pinicial: 196, pfinal: 201, prop: 203, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Histologia Animal", volume: 4, frente: 3, pinicial: 222, pfinal: 231, prop: 232, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false }
              ]
            },
            {
              subject: "Física",
              topics: [
                { assunto: "Introdução à Cinemática", volume: 1, frente: 1, pinicial: 6, pfinal: 12, prop: 13, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "A natureza elétrica da matéria e a Lei de Coloumb", volume: 1, frente: 2, pinicial: 132, pfinal: 147, prop: 148, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Termometria", volume: 1, frente: 3, pinicial: 256, pfinal: 263, prop: 265, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Movimento Uniforme", volume: 1, frente: 1, pinicial: 26, pfinal: 28, prop: 30, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Campo elétrico", volume: 1, frente: 2, pinicial: 166, pfinal: 178, prop: 179, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Dilatação térmica", volume: 1, frente: 3, pinicial: 274, pfinal: 283, prop: 285, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Movimento Uniformemente Variado", volume: 1, frente: 1, pinicial: 42, pfinal: 51, prop: 54, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Potencial Elétrico", volume: 1, frente: 2, pinicial: 196, pfinal: 210, prop: 212, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Calorimetria", volume: 1, frente: 3, pinicial: 298, pfinal: 304, prop: 307, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Análise Gráfica", volume: 1, frente: 1, pinicial: 68, pfinal: 77, prop: 79, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Corrente elétrica", volume: 1, frente: 2, pinicial: 232, pfinal: 263, prop: 242, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Mudanças de estado físico", volume: 1, frente: 3, pinicial: 320, pfinal: 328, prop: 332, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Movimento Circular", volume: 1, frente: 1, pinicial: 108, pfinal: 115, prop: 116, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Transferência de calor", volume: 1, frente: 3, pinicial: 342, pfinal: 350, prop: 353, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Gases e termodinâmica", volume: 1, frente: 3, pinicial: 364, pfinal: 383, prop: 385, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Cinemática Vetorial", volume: 2, frente: 1, pinicial: 6, pfinal: 21, prop: 23, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Resistores", volume: 2, frente: 2, pinicial: 132, pfinal: 146, prop: 132, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Óptica geométrica", volume: 2, frente: 3, pinicial: 258, pfinal: 268, prop: 271, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Lançamento Oblíquo no Vácuo", volume: 2, frente: 1, pinicial: 46, pfinal: 51, prop: 54, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Circuitos elétricos", volume: 2, frente: 2, pinicial: 166, pfinal: 181, prop: 183, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Reflexão da luz", volume: 2, frente: 3, pinicial: 278, pfinal: 298, prop: 300, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Dinâmica", volume: 2, frente: 1, pinicial: 74, pfinal: 89, prop: 93, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Interação entre cargas elétricas e campo magnético", volume: 2, frente: 2, pinicial: 210, pfinal: 213, prop: 215, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Refração da luz", volume: 2, frente: 3, pinicial: 324, pfinal: 339, prop: 341, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Fontes de campo magnético", volume: 2, frente: 2, pinicial: 234, pfinal: 238, prop: 239, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Força de atrito e dinâmica no Movimento Circular", volume: 3, frente: 1, pinicial: 6, pfinal: 14, prop: 20, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Forças magnéticas e indução magnética", volume: 3, frente: 2, pinicial: 122, pfinal: 135, prop: 137, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Óptica da visão e instrumentos ópticos", volume: 3, frente: 3, pinicial: 228, pfinal: 242, prop: 244, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Trabalho, potência e energia", volume: 3, frente: 1, pinicial: 52, pfinal: 68, prop: 76, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Gravitação", volume: 3, frente: 2, pinicial: 166, pfinal: 187, prop: 190, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Movimentos oscilatórios periódicos", volume: 3, frente: 3, pinicial: 264, pfinal: 275, prop: 277, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Introdução à Ondulatória", volume: 3, frente: 3, pinicial: 292, pfinal: 301, prop: 303, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Impulso, quantidade de movimento, colisões, centro de massa e análise dimensional", volume: 4, frente: 1, pinicial: 6, pfinal: 16, prop: 22, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Estática", volume: 4, frente: 2, pinicial: 66, pfinal: 84, prop: 87, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Ondas periódicas", volume: 4, frente: 3, pinicial: 182, pfinal: 190, prop: 193, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Hidrostática", volume: 4, frente: 2, pinicial: 124, pfinal: 140, prop: 144, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Interferência", volume: 4, frente: 3, pinicial: 208, pfinal: 216, prop: 219, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                  { assunto: "Acústica", volume: 4, frente: 3, pinicial: 238, pfinal: 249, prop: 251, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false }
                ]
              },
              {
                subject: "Química",
                topics: [
                  { assunto: "O átomo", volume: 1, frente: 1, pinicial: 6, pfinal: 23, prop: 26 },
                  { assunto: "Determinação de fórmulas", volume: 1, frente: 2, pinicial: 196, pfinal: 199, prop: 201 },
                  { assunto: "Gases", volume: 1, frente: 3, pinicial: 268, pfinal: 288, prop: 291 },
                  { assunto: "Tabela periódica", volume: 1, frente: 1, pinicial: 54, pfinal: 65, prop: 67 },
                  { assunto: "Cálculo estequiométrico", volume: 1, frente: 2, pinicial: 210, pfinal: 216, prop: 218 },
                  { assunto: "Teoria atômico-molecular", volume: 1, frente: 3, pinicial: 246, pfinal: 252, prop: 255 },
                  { assunto: "Ligações químicas", volume: 1, frente: 1, pinicial: 90, pfinal: 109, prop: 113 },
                  { assunto: "Estados físicos e suas mudanças", volume: 1, frente: 1, pinicial: 160, pfinal: 172, prop: 173 },
                  { assunto: "Termoquímica", volume: 1, frente: 3, pinicial: 322, pfinal: 334, prop: 339 },
                  { assunto: "Propriedades físicas", volume: 2, frente: 1, pinicial: 6, pfinal: 12, prop: 14 },
                  { assunto: "Ácidos e Bases I - Teoria, Funções", volume: 2, frente: 2, pinicial: 178, pfinal: 180, prop: 190 },
                  { assunto: "Ácidos e Bases II - Ácidos e bases", volume: 2, frente: 2, pinicial: 181, pfinal: 190, prop: 190 },
                  { assunto: "Cinética Química I - Velocidade, teoria das colisões", volume: 2, frente: 3, pinicial: 284, pfinal: 293, prop: 301 },
                  { assunto: "Introdução à Química Orgânica", volume: 2, frente: 1, pinicial: 30, pfinal: 39, prop: 42 },
                  { assunto: "Sais e óxidos I - Sais", volume: 2, frente: 2, pinicial: 206, pfinal: 214, prop: 222 },
                  { assunto: "Cinética Química II - Lei de Guldberg-Waage", volume: 2, frente: 3, pinicial: 293, pfinal: 296, prop: 301 },
                  { assunto: "Nomenclatura dos Compostos Orgânicos I - Hidrocarbonetos", volume: 2, frente: 1, pinicial: 58, pfinal: 68, prop: 82 },
                  { assunto: "Sais e óxidos II - Óxidos", volume: 2, frente: 2, pinicial: 214, pfinal: 220, prop: 222 },
                  { assunto: "Nomenclatura dos Compostos Orgânicos II - Haletos, álcool e fenol", volume: 2, frente: 1, pinicial: 69, pfinal: 71, prop: 82 },
                  { assunto: "Soluções I - Dispersões, soluções e coeficiente", volume: 2, frente: 2, pinicial: 244, pfinal: 253, prop: 258 },
                  { assunto: "Equilíbrios químicos I - Reações reversíveis, grau de equilíbrio e constantes de equilíbrio", volume: 2, frente: 3, pinicial: 334, pfinal: 344, prop: 358 },
                  { assunto: "Nomenclatura dos Compostos Orgânicos III - Éter, aldeído e cetona", volume: 2, frente: 1, pinicial: 71, pfinal: 74, prop: 82 },
                  { assunto: "Nomenclatura dos Compostos Orgânicos IV - Ácidos carboxílicos e sais, éster org.", volume: 2, frente: 1, pinicial: 74, pfinal: 75, prop: 82 },
                  { assunto: "Soluções II - Diluição e Misturas, Titulação", volume: 2, frente: 2, pinicial: 254, pfinal: 257, prop: 258 },
                  { assunto: "Equilíbrios químicos I - Le Chatelier e Equilíbrios iônicos", volume: 2, frente: 3, pinicial: 344, pfinal: 352, prop: 358 },
                  { assunto: "Nomenclatura dos Compostos Orgânicos V - Amina, Amida, Nitrilas e Nitrocompostos", volume: 2, frente: 1, pinicial: 76, pfinal: 77, prop: 82 },
                  { assunto: "Nomenclatura dos Compostos Orgânicos VI - Tiocompostos, enol", volume: 2, frente: 1, pinicial: 79, pfinal: 79, prop: 82 },
                  { assunto: "Isomeria I - Plana", volume: 2, frente: 1, pinicial: 136, pfinal: 138, prop: 147 },
                  { assunto: "Isomeria II - Espacial", volume: 2, frente: 1, pinicial: 139, pfinal: 146, prop: 147 },
                  { assunto: "Propriedades Coligativas I - Definição, Tonometria e Ebuliometria", volume: 3, frente: 2, pinicial: 84, pfinal: 89, prop: 96 },
                  { assunto: "Equilíbrio químico II - Água, conceitos modernos", volume: 3, frente: 3, pinicial: 146, pfinal: 148, prop: 169 },
                  { assunto: "Reações orgânicas I - Cisão", volume: 3, frente: 1, pinicial: 6, pfinal: 6, prop: 32 },
                  { assunto: "Reações orgânicas II - Substituição", volume: 3, frente: 1, pinicial: 6, pfinal: 14, prop: 32 },
                  { assunto: "Propriedades Coligativas II - Criometria e Osmometria", volume: 3, frente: 2, pinicial: 89, pfinal: 93, prop: 96 },
                  { assunto: "Equilíbrio químico II - Equilíbrios heterogêneos", volume: 3, frente: 3, pinicial: 159, pfinal: 166, prop: 169 },
                  { assunto: "Reações orgânicas III - Adição", volume: 3, frente: 1, pinicial: 15, pfinal: 27, prop: 32 },
                  { assunto: "Oxirredução I - NOX", volume: 3, frente: 2, pinicial: 118, pfinal: 122, prop: 130 },
                  { assunto: "Oxirredução II - Agentes", volume: 3, frente: 2, pinicial: 123, pfinal: 130, prop: 130 },
                  { assunto: "Caráter ácido-básico de substâncias orgânicas I - Caráter ácido", volume: 4, frente: 1, pinicial: 6, pfinal: 9, prop: 13 },
                  { assunto: "Caráter ácido-básico de substâncias orgânicas II - Caráter básico e anfótero dos aminoácidos", volume: 4, frente: 1, pinicial: 9, pfinal: 11, prop: 13 },
                  { assunto: "Radioatividade I - Histórico e emissões", volume: 4, frente: 2, pinicial: 136, pfinal: 138, prop: 151 },
                  { assunto: "Eletroquímica I - Introdução, Pilha de Daniell", volume: 4, frente: 3, pinicial: 214, pfinal: 221, prop: 240 },
                  { assunto: "Polímeros I - Classificação, polímeros de adição", volume: 4, frente: 1, pinicial: 30, pfinal: 38, prop: 45 },
                  { assunto: "Polímeros II - Polímeros de condensação", volume: 4, frente: 1, pinicial: 38, pfinal: 42, prop: 45 },
                  { assunto: "Radioatividade II - Reações nucleares", volume: 4, frente: 2, pinicial: 138, pfinal: 144, prop: 151 },
                  { assunto: "Eletroquímica II - Tipos de pilha", volume: 4, frente: 3, pinicial: 221, pfinal: 227, prop: 240 },
                  { assunto: "Bioquímica I - Aminoácidos", volume: 4, frente: 1, pinicial: 72, pfinal: 78, prop: 85 },
                  { assunto: "Bioquímica II - Lipídeos e fosfolipídeos", volume: 4, frente: 1, pinicial: 78, pfinal: 80, prop: 85 },
                  { assunto: "Reações inorgânicas I - Síntese e análise", volume: 4, frente: 2, pinicial: 174, pfinal: 179, prop: 182 },
                  { assunto: "Eletroquímica III - Eletrólises I", volume: 4, frente: 3, pinicial: 227, pfinal: 230, prop: 250 },
                  { assunto: "Bioquímica III - Carboidratos", volume: 4, frente: 1, pinicial: 80, pfinal: 84, prop: 85 },
                  { assunto: "Reações inorgânicas I - Dupla troca", volume: 4, frente: 2, pinicial: 179, pfinal: 180, prop: 182 },
                  { assunto: "Recursos orgânicos I - Petróleo, gás natural", volume: 4, frente: 1, pinicial: 112, pfinal: 117, prop: 121 },
                  { assunto: "Recursos orgânicos II - Carvão mineral, xisto", volume: 4, frente: 1, pinicial: 117, pfinal: 118, prop: 121 },
                  { assunto: "Eletroquímica III - Eletrólises II", volume: 4, frente: 3, pinicial: 230, pfinal: 232, prop: 250 },
                  { assunto: "Eletroquímica IV - Eletroquímica quantitativa", volume: 4, frente: 3, pinicial: 232, pfinal: 234, prop: 250 },
                  { assunto: "Recursos orgânicos III - Biocombustível", volume: 4, frente: 1, pinicial: 118, pfinal: 120, prop: 121 }
                ]
              },
             {
              subject: "Geografia",
              topics: [
                { assunto: "Noções espaciais e cartografia I - Movimentos, Coordenadas", volume: 1, frente: 1, pinicial: 6, pfinal: 12, prop: 25, view: "2025-01-13T12:00:00.000Z" },
                { assunto: "Noções espaciais e cartografia II - Representações, tipos de mapas", volume: 1, frente: 1, pinicial: 12, pfinal: 19, prop: 25, view: "2025-02-13T12:00:00.000Z" },
                { assunto: "Noções espaciais e cartografia III - Projeções, sensoriamento", volume: 1, frente: 1, pinicial: 19, pfinal: 24, prop: 25, view: "2025-03-13T12:00:00.000Z" },
                { assunto: "Geomorfologia I - Formação do relevo, tipos de rocha, forças internas I", volume: 1, frente: 1, pinicial: 46, pfinal: 49, prop: 74, view: "2025-02-14T12:00:00.000Z" },
                { assunto: "Geomorfologia II - Forças internas II", volume: 1, frente: 1, pinicial: 49, pfinal: 57, prop: 74, view: "2025-03-14T12:00:00.000Z" },
                { assunto: "Geomorfologia III - Processos, relevo mundial I", volume: 1, frente: 1, pinicial: 57, pfinal: 58, prop: 74, view: "2025-04-14T12:00:00.000Z" },
                { assunto: "Geomorfologia IV - Relevo mundial II, Relevo do Brasil", volume: 1, frente: 1, pinicial: 58, pfinal: 71, prop: 74, view: "2025-05-14T12:00:00.000Z" },
                { assunto: "Solos I - Solo, tipos de solo", volume: 1, frente: 1, pinicial: 98, pfinal: 103, prop: 109, view: "2025-03-04T12:00:00.000Z" },
                { assunto: "Solos II - Manejo do solo e riscos de degradação", volume: 1, frente: 1, pinicial: 103, pfinal: 108, prop: 109, view: "2025-04-04T12:00:00.000Z" },
                { assunto: "Espaço geográfico I - Objeto, história", volume: 1, frente: 2, pinicial: 138, pfinal: 142, prop: 149, view: "2025-01-16T12:00:00.000Z" },
                { assunto: "Espaço geográfico II - Geografia e o mundo", volume: 1, frente: 2, pinicial: 142, pfinal: 146, prop: 149, view: "2025-02-16T12:00:00.000Z" },
                { assunto: "Espaço geográfico III - Evolução histórica", volume: 1, frente: 2, pinicial: 146, pfinal: 148, prop: 149, view: "2025-03-16T12:00:00.000Z" },
                { assunto: "Globalização I - Capitalismo na produção do espaço geográfico I", volume: 1, frente: 2, pinicial: 158, pfinal: 164, prop: 179, view: "2025-02-25T12:00:00.000Z" },
                { assunto: "Globalização II - Capitalismo na produção do espaço geográfico II", volume: 1, frente: 2, pinicial: 164, pfinal: 169, prop: 179, view: "2025-03-25T12:00:00.000Z" },
                { assunto: "Globalização III - Avanço da globalização I", volume: 1, frente: 2, pinicial: 169, pfinal: 173, prop: 179, view: "2025-04-25T12:00:00.000Z" },
                { assunto: "Globalização IV - Avanço da globalização II", volume: 1, frente: 2, pinicial: 173, pfinal: 177, prop: 179, view: "2025-05-25T12:00:00.000Z" },
                { assunto: "Indústria I - Indústria e espaço, tipos de indústrias", volume: 1, frente: 2, pinicial: 206, pfinal: 211, prop: 243, view: "2025-03-07T12:00:00.000Z" },
                { assunto: "Mineração I - Tipos", volume: 1, frente: 1, pinicial: 118, pfinal: 120, prop: 128 },
  { assunto: "Indústria II - A localização industrial", volume: 1, frente: 2, pinicial: 211, pfinal: 213, prop: 243 },
  { assunto: "Indústria III - Org. da prod. industrial", volume: 1, frente: 2, pinicial: 213, pfinal: 219, prop: 243 },
  { assunto: "Mineração II - Minerais metálicos I", volume: 1, frente: 1, pinicial: 120, pfinal: 125, prop: 128 },
  { assunto: "Indústria IV - Prod. industrial mundial I", volume: 1, frente: 2, pinicial: 219, pfinal: 224, prop: 243 },
  { assunto: "Indústria V - Prod. industrial mundial II", volume: 1, frente: 2, pinicial: 224, pfinal: 228, prop: 243 },
  { assunto: "Mineração III - Minerais metálicos II e Impactos", volume: 1, frente: 1, pinicial: 125, pfinal: 127, prop: 128 },
  { assunto: "Indústria VI - Industrialização brasileira I", volume: 1, frente: 2, pinicial: 228, pfinal: 233, prop: 243 },
  { assunto: "Indústria VII - Industrialização brasileira II", volume: 1, frente: 2, pinicial: 233, pfinal: 238, prop: 243 },
  { assunto: "Indústria VIII - Industrialização brasileira III", volume: 1, frente: 2, pinicial: 238, pfinal: 241, prop: 243 },
  { assunto: "Climatologia I - Fundamentos I", volume: 2, frente: 1, pinicial: 6, pfinal: 11, prop: 27 },
  { assunto: "Climatologia II - Fundamentos II", volume: 2, frente: 1, pinicial: 11, pfinal: 14, prop: 27 },
  { assunto: "Climatologia III - Circulação atmosférica I", volume: 2, frente: 1, pinicial: 14, pfinal: 18, prop: 27 },
  { assunto: "Geografia Agrária I - Sistemas agrícolas I", volume: 2, frente: 2, pinicial: 136, pfinal: 140, prop: 174 },
  { assunto: "Geografia Agrária II - Sistemas agrícolas II", volume: 2, frente: 2, pinicial: 141, pfinal: 144, prop: 174 },
  { assunto: "Climatologia IV - Circulação atmosférica II", volume: 2, frente: 1, pinicial: 18, pfinal: 23, prop: 27 },
  { assunto: "Climatologia V - Circulação atmosférica III", volume: 2, frente: 1, pinicial: 23, pfinal: 26, prop: 27 },
  { assunto: "Geografia Agrária III - Campo brasileiro I", volume: 2, frente: 2, pinicial: 144, pfinal: 147, prop: 174 },
  { assunto: "Geografia Agrária IV - Campo brasileiro II", volume: 2, frente: 2, pinicial: 148, pfinal: 151, prop: 174 },
  { assunto: "Hidrografia I - Hidrologia I", volume: 2, frente: 1, pinicial: 52, pfinal: 58, prop: 78 },
  { assunto: "Hidrografia II - Hidrologia II", volume: 2, frente: 1, pinicial: 58, pfinal: 63, prop: 78 },
  { assunto: "Geografia Agrária V - Questão agrária I", volume: 2, frente: 2, pinicial: 165, pfinal: 169, prop: 174 },
  { assunto: "Hidrografia III - Hidrografia mundial I", volume: 2, frente: 1, pinicial: 63, pfinal: 66, prop: 78 },
  { assunto: "Geografia Agrária VI - Questão agrária II", volume: 2, frente: 2, pinicial: 170, pfinal: 173, prop: 174 },
  { assunto: "Hidrografia IV - Hidrografia mundial II", volume: 2, frente: 1, pinicial: 67, pfinal: 69, prop: 78 },
  { assunto: "Hidrografia V - Hidrografia do Brasil I", volume: 2, frente: 1, pinicial: 69, pfinal: 72, prop: 78 },
  { assunto: "Energia I - Uso, desigualdade, tipos, matriz", volume: 2, frente: 2, pinicial: 192, pfinal: 196, prop: 230 },
  { assunto: "Energia II - Combustíveis fósseis", volume: 2, frente: 2, pinicial: 196, pfinal: 200, prop: 230 },
  { assunto: "Hidrografia V - Hidrografia do Brasil II", volume: 2, frente: 1, pinicial: 73, pfinal: 76, prop: 78 },
  { assunto: "Energia III - Outras fontes", volume: 2, frente: 2, pinicial: 200, pfinal: 205, prop: 230 },
  { assunto: "Relações internacionais I - Espaço, funcionamento I", volume: 2, frente: 2, pinicial: 290, pfinal: 293, prop: 298 },
  { assunto: "Relações internacionais II - Funcionamento II", volume: 2, frente: 2, pinicial: 294, pfinal: 297, prop: 298 },
  { assunto: "Demografia I - Estudos populacionais, teorias, dinâmicas", volume: 3, frente: 1, pinicial: 6, pfinal: 10, prop: 32 },
  { assunto: "Demografia II - Dinâmicas II, Pirâmides etárias", volume: 3, frente: 1, pinicial: 13, pfinal: 20, prop: 32 },
  { assunto: "Ordem mundial I - Ordem mundial, Guerra Fria", volume: 3, frente: 2, pinicial: 92, pfinal: 101, prop: 128 },
  { assunto: "Ordem mundial II - NOM", volume: 3, frente: 2, pinicial: 101, pfinal: 106, prop: 128 },
  { assunto: "Demografia III - Estrutura étnica brasileira", volume: 3, frente: 1, pinicial: 20, pfinal: 27, prop: 32 },
  { assunto: "Ordem mundial III - Centros de poder: UE I", volume: 3, frente: 2, pinicial: 106, pfinal: 111, prop: 128 },
  { assunto: "Demografia IV - Fluxos internacionais e imigração no Brasil", volume: 3, frente: 1, pinicial: 27, pfinal: 31, prop: 32 },
  { assunto: "Urbanização I I - Cidade e espaço urbano, cidade e município, tipos de cidades", volume: 3, frente: 1, pinicial: 58, pfinal: 61, prop: 75 },
  { assunto: "Ordem mundial IV - Centros de poder: UE II", volume: 3, frente: 2, pinicial: 111, pfinal: 115, prop: 128 },
  { assunto: "Ordem mundial V - BRICS I", volume: 3, frente: 2, pinicial: 115, pfinal: 120, prop: 128 },
  { assunto: "Urbanização I II - Urbanização", volume: 3, frente: 1, pinicial: 61, pfinal: 67, prop: 75 },
  { assunto: "Ordem mundial V - BRICS II", volume: 3, frente: 2, pinicial: 121, pfinal: 126, prop: 128 },
  { assunto: "África I - Características básicas, colonialismo", volume: 3, frente: 2, pinicial: 162, pfinal: 166, prop: 176 },
  { assunto: "Urbanização I III - Redes e hierarquias, metropolização I", volume: 3, frente: 1, pinicial: 67, pfinal: 71, prop: 75 },
  { assunto: "África II - Divisões do continente I", volume: 3, frente: 2, pinicial: 166, pfinal: 170, prop: 176 },
  { assunto: "Urbanização I III - Metropolização II", volume: 3, frente: 1, pinicial: 71, pfinal: 92, prop: 75 },
  { assunto: "África III - Divisões do continente II, Perspectivas", volume: 3, frente: 2, pinicial: 171, pfinal: 176, prop: 176 },
  { assunto: "Urbanização II I - Problemas urbanos, Problemas sociais urbanos I", volume: 4, frente: 1, pinicial: 6, pfinal: 11, prop: 24 },
  { assunto: "África II I - Conflitos, passado recente e atualidade, Primavera Árabe I", volume: 4, frente: 2, pinicial: 106, pfinal: 110, prop: 117 },
  { assunto: "Urbanização II II - Problemas sociais urbanos II, Problemas socioambientais urbanos I", volume: 4, frente: 1, pinicial: 12, pfinal: 17, prop: 24 },
  { assunto: "Urbanização II I - Problemas socioambientais urbanos II", volume: 4, frente: 1, pinicial: 18, pfinal: 23, prop: 24 },
  { assunto: "África II II - Primavera Árabe II", volume: 4, frente: 2, pinicial: 111, pfinal: 115, prop: 117 },
  { assunto: "Questões ambientais I - A questão, principais problemas", volume: 4, frente: 1, pinicial: 42, pfinal: 47, prop: 59 },
  { assunto: "Questões ambientais II - Mudanças climáticas", volume: 4, frente: 1, pinicial: 48, pfinal: 51, prop: 59 },
  { assunto: "Oriente Médio I - A região", volume: 4, frente: 2, pinicial: 128, pfinal: 131, prop: 149 },
  { assunto: "Oriente Médio II - A Guerra da Palestina I", volume: 4, frente: 2, pinicial: 132, pfinal: 135, prop: 149 },
  { assunto: "Oriente Médio III - A Guerra da Palestina II", volume: 4, frente: 2, pinicial: 136, pfinal: 140, prop: 149 },
  { assunto: "Questões ambientais III - Principais problemas, geopolítica ambiental", volume: 4, frente: 1, pinicial: 51, pfinal: 54, prop: 59 },
  { assunto: "Oriente Médio IV - A Guerra da Palestina III, Conflitos I", volume: 4, frente: 2, pinicial: 141, pfinal: 145, prop: 149 },
  { assunto: "Questões ambientais IV - Preservacionistas e conservacionistas, Regulação ambiental no Brasil", volume: 4, frente: 1, pinicial: 55, pfinal: 58, prop: 59 },
  { assunto: "Regionalização do Brasil I - Organização política, Federação Brasileira", volume: 4, frente: 1, pinicial: 74, pfinal: 77, prop: 91 },
  { assunto: "Oriente Médio V - Conflitos II", volume: 4, frente: 2, pinicial: 145, pfinal: 147, prop: 149 },
  { assunto: "Regionalização do Brasil II - Presidencialismo e parlamentarismo, as regiões brasileiras, as cinco macrorregiões", volume: 4, frente: 1, pinicial: 77, pfinal: 81, prop: 91 },
  { assunto: "Regionalização do Brasil III - Complexos regionais I", volume: 4, frente: 1, pinicial: 81, pfinal: 85, prop: 91 },
  { assunto: "América Latina I - A América I", volume: 4, frente: 2, pinicial: 170, pfinal: 174, prop: 187 },
  { assunto: "América Latina II - A América II, Conflitos e tensões I", volume: 4, frente: 2, pinicial: 175, pfinal: 179, prop: 187 },
  { assunto: "Regionalização do Brasil IV - Complexos regionais II, quatro Brasis", volume: 4, frente: 1, pinicial: 86, pfinal: 90, prop: 91 },
  { assunto: "América Latina III - Conflitos e tensões II", volume: 4, frente: 2, pinicial: 180, pfinal: 185, prop: 187 }
              ]
             }
            {
              subject: "Filosofia",
              topics: [
                { assunto: "Introdução à Filosofia", volume: 1, frente: 1, pinicial: 6, pfinal: 9, prop: 14, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "A Filosofia ao longo da História", volume: 1, frente: 1, pinicial: 10, pfinal: 12, prop: 14, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "O nascimento da Filosofia", volume: 1, frente: 1, pinicial: 18, pfinal: 21, prop: 23, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Sócrates", volume: 1, frente: 1, pinicial: 28, pfinal: 31, prop: 33, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Platão", volume: 1, frente: 1, pinicial: 38, pfinal: 38, prop: 44, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Platão - A República e o Timeu", volume: 1, frente: 1, pinicial: 39, pfinal: 42, prop: 44, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Aristóteles", volume: 1, frente: 1, pinicial: 50, pfinal: 54, prop: 57, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Helenística - O período helenístico e epicurismo", volume: 1, frente: 1, pinicial: 62, pfinal: 62, prop: 67, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Helenística - Estoicismo e Ceticismo", volume: 1, frente: 1, pinicial: 63, pfinal: 64, prop: 67, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Medieval - Patrística e Agostinho", volume: 1, frente: 1, pinicial: 72, pfinal: 73, prop: 80, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Medieval - Escolástica", volume: 1, frente: 1, pinicial: 74, pfinal: 75, prop: 80, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Medieval - Tomás de Aquino", volume: 1, frente: 1, pinicial: 75, pfinal: 77, prop: 80, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia do Renascimento - Humanismo", volume: 1, frente: 1, pinicial: 86, pfinal: 87, prop: 95, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia do Renascimento - Maquiavel", volume: 1, frente: 1, pinicial: 88, pfinal: 89, prop: 95, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia do Renascimento - Rev. Científica", volume: 1, frente: 1, pinicial: 90, pfinal: 92, prop: 95, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Moderna - Racionalismo", volume: 1, frente: 1, pinicial: 102, pfinal: 105, prop: 114, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Moderna - Empirismo", volume: 1, frente: 1, pinicial: 106, pfinal: 109, prop: 114, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Moderna - Criticismo", volume: 1, frente: 1, pinicial: 109, pfinal: 112, prop: 114, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Moderna - Utilitarismo", volume: 1, frente: 1, pinicial: 120, pfinal: 121, prop: 129, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Moderna - Ética deontológica", volume: 1, frente: 1, pinicial: 122, pfinal: 123, prop: 129, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Moderna - Contratualismo", volume: 1, frente: 1, pinicial: 124, pfinal: 127, prop: 129, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Contemporânea - Hegel", volume: 1, frente: 1, pinicial: 138, pfinal: 139, prop: 148, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Contemporânea - Marx e Schopenhauer", volume: 1, frente: 1, pinicial: 140, pfinal: 141, prop: 148, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Contemporânea - Kierkegaard e Nietzsche", volume: 1, frente: 1, pinicial: 142, pfinal: 153, prop: 148, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false },
                { assunto: "Filosofia Contemporânea - IA", volume: 1, frente: 1, pinicial: 196, pfinal: 198, prop: 201, stars: 0, difficult: 0, revisoes: 0, rev1: null, rev1details: {}, concluido: false }
              ]
            }
            {
              subject: "Matemática",
              topics: [
                { assunto: "Teoria elementar dos conjuntos", volume: 1, frente: 1, pinicial: 6, pfinal: 14, prop: 15 },
                { assunto: "Conjuntos numéricos I - Naturais, inteiros", volume: 1, frente: 2, pinicial: 120, pfinal: 136, prop: 154 },
                { assunto: "Ferramentas básicas da Geometria", volume: 1, frente: 3, pinicial: 246, pfinal: 258, prop: 261 },
                { assunto: "Relações e funções", volume: 1, frente: 1, pinicial: 26, pfinal: 33, prop: 34 },
                { assunto: "Função do 1° Grau", volume: 1, frente: 1, pinicial: 50, pfinal: 53, prop: 55 },
                { assunto: "Conjuntos numéricos II - Racionais, reais", volume: 1, frente: 2, pinicial: 136, pfinal: 146, prop: 154 },
                { assunto: "Princípios de Geometria Plana I - Euclides", volume: 1, frente: 3, pinicial: 272, pfinal: 273, prop: 298 },
                { assunto: "Princípios de Geometria Plana II - Congruência de Triângulos, Ângulos, Círculos e circunferências", volume: 1, frente: 3, pinicial: 279, pfinal: 289, prop: 298 },
                { assunto: "Função inversa e função composta", volume: 1, frente: 1, pinicial: 66, pfinal: 69, prop: 70 },
                { assunto: "Conjuntos numéricos II - Teoria fundamental da Aritmética, Sistema decimal", volume: 1, frente: 2, pinicial: 146, pfinal: 151, prop: 154 },
                { assunto: "Princípios de Geometria Plana III - Polígonos", volume: 1, frente: 3, pinicial: 290, pfinal: 294, prop: 298 },
                { assunto: "Função do 2° Grau", volume: 1, frente: 1, pinicial: 80, pfinal: 88, prop: 91 },
                { assunto: "Teoria das proporções geométricas I - Div. segmento e Tales", volume: 1, frente: 3, pinicial: 316, pfinal: 319, prop: 334 },
                { assunto: "Teoria das proporções geométricas II - Semelhança de triângulos", volume: 1, frente: 3, pinicial: 320, pfinal: 323, prop: 334 },
                { assunto: "Função Exponencial I - Equações e Funções", volume: 1, frente: 1, pinicial: 102, pfinal: 104, prop: 109 },
                { assunto: "Sentenças matemáticas e modelagens algébricas I - Sentenças, técnicas", volume: 1, frente: 2, pinicial: 174, pfinal: 180, prop: 190 },
                { assunto: "Teoria das proporções geométricas III - Consequências de semelhança e Tales", volume: 1, frente: 3, pinicial: 324, pfinal: 331, prop: 334 },
                { assunto: "Função Exponencial II - Translação e Reflexão", volume: 1, frente: 1, pinicial: 104, pfinal: 105, prop: 109 },
                { assunto: "Sentenças matemáticas e modelagens algébricas II - Problemas do 1° e 2° Grau", volume: 1, frente: 2, pinicial: 181, pfinal: 187, prop: 190 },
                { assunto: "Teorema dos Senos e Cossenos I - Classificação, ângulos obtusos, relações em triângulos quaisquer", volume: 1, frente: 3, pinicial: 354, pfinal: 356, prop: 367 },
                { assunto: "Teorema dos Senos e Cossenos II - Cevianas de triângulos", volume: 1, frente: 3, pinicial: 362, pfinal: 364, prop: 367 },
                { assunto: "Função Exponencial III - Inequações", volume: 1, frente: 1, pinicial: 106, pfinal: 107, prop: 109 },
                { assunto: "Centros dos triângulos e polígonos I - Triângulo", volume: 1, frente: 3, pinicial: 376, pfinal: 381, prop: 390 },
                { assunto: "Razões e proporções", volume: 1, frente: 2, pinicial: 206, pfinal: 223, prop: 227 },
                { assunto: "Centros dos triângulos e polígonos II - Polígonos regulares", volume: 1, frente: 3, pinicial: 382, pfinal: 388, prop: 390 },
                { assunto: "Função Logarítmica I - Logaritmos, equações", volume: 2, frente: 1, pinicial: 6, pfinal: 10, prop: 17 },
                { assunto: "Análise de grandezas proporcionais I - Dedução, variação", volume: 2, frente: 2, pinicial: 92, pfinal: 102, prop: 110 },
                { assunto: "Área das figuras planas I - grandeza, equivalência, fórmulas", volume: 2, frente: 3, pinicial: 272, pfinal: 283, prop: 299 },
                { assunto: "Função Logarítmica II - Função, inequações", volume: 2, frente: 1, pinicial: 10, pfinal: 15, prop: 17 },
                { assunto: "Análise de grandezas proporcionais II - Aplicação da estrutura de proporcionalidade", volume: 2, frente: 2, pinicial: 102, pfinal: 108, prop: 110 },
                { assunto: "Sequências Numéricas I - Sequências e PA", volume: 2, frente: 2, pinicial: 122, pfinal: 127, prop: 138 },
                { assunto: "Área das figuras planas II - Área do triângulo, polígonos regulares e círculo", volume: 2, frente: 3, pinicial: 283, pfinal: 294, prop: 299 },
                { assunto: "Função Modular I - Função, gráfico", volume: 2, frente: 1, pinicial: 38, pfinal: 41, prop: 45 },
                { assunto: "Função Modular II - Equações e inequações", volume: 2, frente: 1, pinicial: 41, pfinal: 44, prop: 45 },
                { assunto: "Sequências Numéricas II - PG", volume: 2, frente: 2, pinicial: 127, pfinal: 133, prop: 138 },
                { assunto: "Sequências Numéricas III - Outras sequências", volume: 2, frente: 2, pinicial: 133, pfinal: 135, prop: 138 },
                { assunto: "Plano cartesiano I - Introdução, Coordenadas em um eixo", volume: 2, frente: 3, pinicial: 324, pfinal: 326, prop: 333 },
                { assunto: "Plano cartesiano II - Ponto médio, baricentro", volume: 2, frente: 3, pinicial: 326, pfinal: 328, prop: 333 },
                { assunto: "Trigonometria I - Arcos e ângulos, circunferência", volume: 2, frente: 1, pinicial: 56, pfinal: 60, prop: 72 },
                { assunto: "Álgebra linear I - Função linear", volume: 2, frente: 2, pinicial: 162, pfinal: 167, prop: 233 },
                { assunto: "Álgebra linear II - Sistemas lineares", volume: 2, frente: 2, pinicial: 167, pfinal: 173, prop: 233 },
                { assunto: "Plano cartesiano III - Distância entre pontos, área de triângulo, alinhamento", volume: 2, frente: 3, pinicial: 328, pfinal: 332, prop: 333 },
                { assunto: "Trigonometria II - Seno e cosseno", volume: 2, frente: 1, pinicial: 60, pfinal: 64, prop: 72 },
                { assunto: "Álgebra linear III - Matrizes", volume: 2, frente: 2, pinicial: 173, pfinal: 195, prop: 233 },
                { assunto: "Álgebra linear IV - Determinantes", volume: 2, frente: 2, pinicial: 195, pfinal: 214, prop: 233 },
                { assunto: "Estudo da reta I - Teoria angulas, posições relativas", volume: 2, frente: 3, pinicial: 344, pfinal: 355, prop: 359 },
                { assunto: "Estudo da reta II - Ângulo entre retas, distância ponto e reta", volume: 2, frente: 3, pinicial: 355, pfinal: 357, prop: 359 },
                { assunto: "Trigonometria III - Outras razões", volume: 2, frente: 1, pinicial: 64, pfinal: 67, prop: 72 },
                { assunto: "Álgebra linear V - Combinação linear de uma matriz", volume: 2, frente: 2, pinicial: 214, pfinal: 220, prop: 233 },
                { assunto: "Equações da circunferência I - Reduzida e geral", volume: 2, frente: 3, pinicial: 378, pfinal: 381, prop: 390 },
                { assunto: "Álgebra linear VI - Métodos matriciais I", volume: 2, frente: 2, pinicial: 220, pfinal: 226, prop: 233 },
                { assunto: "Álgebra linear VI - Métodos matriciais II", volume: 2, frente: 2, pinicial: 226, pfinal: 232, prop: 233 },
                { assunto: "Equações da circunferência II - Reta e circunferência", volume: 2, frente: 3, pinicial: 381, pfinal: 384, prop: 390 },
                { assunto: "Equações da circunferência III - Duas circunferências", volume: 2, frente: 3, pinicial: 384, pfinal: 387, prop: 390 },
                { assunto: "Transformações trigonométricas", volume: 3, frente: 1, pinicial: 6, pfinal: 10, prop: 29 },
                { assunto: "Estatística I - População e amostra, variáveis estatísticas", volume: 3, frente: 2, pinicial: 80, pfinal: 87, prop: 99 },
                { assunto: "Cônicas I - Seções cônicas I", volume: 3, frente: 3, pinicial: 188, pfinal: 192, prop: 208 },
                { assunto: "Cônicas I - Seções cônicas II", volume: 3, frente: 3, pinicial: 192, pfinal: 199, prop: 208 },
                { assunto: "Funções trigonométricas I", volume: 3, frente: 1, pinicial: 10, pfinal: 15, prop: 29 },
                { assunto: "Estatística II - Medidas de posição/tendência central", volume: 3, frente: 2, pinicial: 87, pfinal: 90, prop: 99 },
                { assunto: "Cônicas II - Gráficos de relações", volume: 3, frente: 3, pinicial: 199, pfinal: 208, prop: 208 },
                { assunto: "Funções trigonométricas II", volume: 3, frente: 1, pinicial: 15, pfinal: 20, prop: 29 },
                { assunto: "Estatística III - Medidas de dispersão", volume: 3, frente: 2, pinicial: 90, pfinal: 97, prop: 99 },
                { assunto: "Posições relativas no espaço I - Geometria posicional, postulados de Euclides", volume: 3, frente: 3, pinicial: 226, pfinal: 231, prop: 236 },
                { assunto: "Posições relativas no espaço II - Diedros e Triedros", volume: 3, frente: 3, pinicial: 231, pfinal: 236, prop: 236 },
                { assunto: "Funções trigonométricas inversas", volume: 3, frente: 1, pinicial: 20, pfinal: 23, prop: 29 },
                { assunto: "Números complexos I - Urgência e equações 3° grau", volume: 3, frente: 2, pinicial: 120, pfinal: 129, prop: 167 },
                { assunto: "Paralelepípedos I - volume, capacidade, unidade", volume: 3, frente: 3, pinicial: 248, pfinal: 251, prop: 270 },
                { assunto: "Paralelepípedos II - Unidades arbitrárias, razão de semelhança, fórmulas para cálculo de volumes", volume: 3, frente: 3, pinicial: 251, pfinal: 259, prop: 270 },
                { assunto: "Equações e inequações trigonométricas", volume: 3, frente: 1, pinicial: 23, pfinal: 27, prop: 29 },
                { assunto: "Números complexos II - A necessidade, conjunto C", volume: 3, frente: 2, pinicial: 129, pfinal: 133, prop: 167 },
                { assunto: "Paralelepípedos III - Elementos do paralelepípedo e do cubo", volume: 3, frente: 3, pinicial: 259, pfinal: 266, prop: 270 },
                { assunto: "Análise combinatória I - Princ. Fund. da Contagem", volume: 3, frente: 1, pinicial: 48, pfinal: 51, prop: 59 },
                { assunto: "Números complexos III - Operações básicas", volume: 3, frente: 2, pinicial: 133, pfinal: 138, prop: 167 },
                { assunto: "Poliedros I - Prismas", volume: 3, frente: 3, pinicial: 281, pfinal: 286, prop: 306 },
                { assunto: "Análise combinatória II - Fatorial", volume: 3, frente: 1, pinicial: 51, pfinal: 52, prop: 59 },
                { assunto: "Números complexos III - Representações geométricas", volume: 3, frente: 2, pinicial: 138, pfinal: 148, prop: 167 },
                { assunto: "Poliedros II - Pirâmides", volume: 3, frente: 3, pinicial: 286, pfinal: 292, prop: 306 },
                { assunto: "Análise combinatória III - Agrupamento", volume: 3, frente: 1, pinicial: 52, pfinal: 58, prop: 59 },
                { assunto: "Números complexos IV - Forma trigonométrica", volume: 3, frente: 2, pinicial: 148, pfinal: 152, prop: 167 },
                { assunto: "Números complexos V - Coordenadas polares", volume: 3, frente: 2, pinicial: 152, pfinal: 163, prop: 167 },
                { assunto: "Poliedros III - Elementos dos poliedros", volume: 3, frente: 3, pinicial: 292, pfinal: 297, prop: 306 },
                { assunto: "Poliedros IV - Poliedros de Platão", volume: 3, frente: 3, pinicial: 297, pfinal: 302, prop: 306 },
                { assunto: "Números binomiais", volume: 4, frente: 1, pinicial: 6, pfinal: 7, prop: 12 },
                { assunto: "Polinômios I - Monômios de uma variável", volume: 4, frente: 2, pinicial: 52, pfinal: 55, prop: 79 },
                { assunto: "Cilindros I - Reto/evolução e oblíquo", volume: 4, frente: 3, pinicial: 128, pfinal: 129, prop: 136 },
                { assunto: "Triângulo de Pascal", volume: 4, frente: 1, pinicial: 7, pfinal: 9, prop: 12 },
                { assunto: "Polinômios II - Binômios", volume: 4, frente: 2, pinicial: 55, pfinal: 56, prop: 79 },
                { assunto: "Polinômios III - Trinômios e polinômios", volume: 4, frente: 2, pinicial: 56, pfinal: 64, prop: 79 },
                { assunto: "Cilindros II - Seção meridiana e cilindro equilátero", volume: 4, frente: 3, pinicial: 129, pfinal: 129, prop: 136 },
                { assunto: "Cilindros III - Seção não meridiana, áreas no cilindro de revolução", volume: 4, frente: 3, pinicial: 129, pfinal: 130, prop: 136 },
                { assunto: "Binômio de Newton", volume: 4, frente: 1, pinicial: 9, pfinal: 11, prop: 12 },
                { assunto: "Polinômios IV - Gráficos de polinômios", volume: 4, frente: 2, pinicial: 64, pfinal: 69, prop: 79 },
                { assunto: "Cilindros IV - Volume, tronco", volume: 4, frente: 3, pinicial: 130, pfinal: 132, prop: 136 },
                { assunto: "Polinômios V - Operações com polinômios", volume: 4, frente: 2, pinicial: 69, pfinal: 77, prop: 79 },
                { assunto: "Cones e esferas I - Cones", volume: 4, frente: 3, pinicial: 146, pfinal: 150, prop: 166 },
                { assunto: "Cones e esferas II - Esferas", volume: 4, frente: 3, pinicial: 150, pfinal: 150, prop: 166 },
                { assunto: "Probabilidades I - Experimento e cálculo", volume: 4, frente: 1, pinicial: 20, pfinal: 23, prop: 29 },
                { assunto: "Equações polinomiais I - De uma variável", volume: 4, frente: 2, pinicial: 98, pfinal: 105, prop: 115 },
                { assunto: "Cones e esferas III - Arquimedes, inscrições e circunscrições", volume: 4, frente: 3, pinicial: 150, pfinal: 159, prop: 166 },
                { assunto: "Cones e esferas IV - Sólidos de revolução", volume: 4, frente: 3, pinicial: 159, pfinal: 161, prop: 166 },
                { assunto: "Probabilidades II - Condicional", volume: 4, frente: 1, pinicial: 23, pfinal: 27, prop: 29 },
                { assunto: "Equações polinomiais II - Raízes X soluções", volume: 4, frente: 2, pinicial: 105, pfinal: 112, prop: 115 },
                { assunto: "Troncos I - Semelhança de sólidos e paralelismo", volume: 4, frente: 3, pinicial: 189, pfinal: 190, prop: 195 },
                { assunto: "Probabilidades III - Distribuição binomial", volume: 4, frente: 1, pinicial: 27, pfinal: 28, prop: 29 },
                { assunto: "Equações polinomiais III - Relações coeficientes e raízes", volume: 4, frente: 2, pinicial: 112, pfinal: 113, prop: 115 },
                { assunto: "Troncos II - Troncos de cone e pirâmide", volume: 4, frente: 3, pinicial: 190, pfinal: 193, prop: 195 }
              ]
            }
            {
              subject: "História",
              topics: [
                { assunto: "Formação dos reinos ibéricos", volume: 1, frente: 1, pinicial: 6, pfinal: 14, prop: 16 },
  { assunto: "História e Pré-História", volume: 1, frente: 2, pinicial: 110, pfinal: 117, prop: 120 },
  { assunto: "Formação das estruturas coloniais I - Pioneirismo, Povos indígenas", volume: 1, frente: 1, pinicial: 30, pfinal: 37, prop: 54 },
  { assunto: "Os povos do Oriente e norte africano na Antiguidade I - Onde viviam, organização, economia e sociedade", volume: 1, frente: 2, pinicial: 130, pfinal: 138, prop: 143 },
  { assunto: "Formação das estruturas coloniais II - Período pré-colonial, montagem", volume: 1, frente: 1, pinicial: 37, pfinal: 39, prop: 54 },
  { assunto: "Os povos do Oriente e norte africano na Antiguidade II - Religião, Antiguidade Oriental", volume: 1, frente: 2, pinicial: 138, pfinal: 142, prop: 143 },
  { assunto: "Formação das estruturas coloniais III - Col. América Espanhola, Empresa açucareira", volume: 1, frente: 1, pinicial: 39, pfinal: 44, prop: 54 },
  { assunto: "Antiguidade Clássica I - Grécia Antiga I", volume: 1, frente: 2, pinicial: 150, pfinal: 155, prop: 172 },
  { assunto: "Antiguidade Clássica II - Grécia Antiga II", volume: 1, frente: 2, pinicial: 155, pfinal: 160, prop: 172 },
  { assunto: "Formação das estruturas coloniais IV - Escravidão, Brasil e África, Sociedade Colonial", volume: 1, frente: 1, pinicial: 44, pfinal: 46, prop: 54 },
  { assunto: "Antiguidade Clássica III - Roma Antiga I", volume: 1, frente: 2, pinicial: 160, pfinal: 165, prop: 172 },
  { assunto: "Antiguidade Clássica IV - Roma Antiga II", volume: 1, frente: 2, pinicial: 165, pfinal: 170, prop: 172 },
  { assunto: "Formação das estruturas coloniais V - Administração e União Ibérica", volume: 1, frente: 1, pinicial: 46, pfinal: 52, prop: 54 },
  { assunto: "Outras Idades Médias I - Origem do termo, Islã", volume: 1, frente: 2, pinicial: 190, pfinal: 196, prop: 205 },
  { assunto: "Outras Idades Médias II - Império Bizantino", volume: 1, frente: 2, pinicial: 196, pfinal: 200, prop: 205 },
  { assunto: "Crise do açúcar ao apogeu do Sistema Colonial I - Restauração e expansão", volume: 1, frente: 1, pinicial: 86, pfinal: 90, prop: 97 },
  { assunto: "Idade Média na Europa Ocidental, início da Modernidade I - Reinos germânicos, apogeu", volume: 1, frente: 2, pinicial: 210, pfinal: 220, prop: 233 },
  { assunto: "Idade Média na Europa Ocidental, início da Modernidade II - Expansão feudal e crise do feudalismo", volume: 1, frente: 2, pinicial: 220, pfinal: 226, prop: 233 },
  { assunto: "Crise do açúcar ao apogeu do Sistema Colonial II - Mineração", volume: 1, frente: 1, pinicial: 90, pfinal: 95, prop: 97 },
  { assunto: "Idade Média na Europa Ocidental, início da Modernidade III - Idade Moderna", volume: 1, frente: 2, pinicial: 226, pfinal: 231, prop: 233 },
  { assunto: "A emancipação da América I - A crise do Antigo Regime, Reformas Pombalinas, Crise do sistema", volume: 2, frente: 1, pinicial: 6, pfinal: 11, prop: 25 },
  { assunto: "Religião e monarquia na Época Moderna I - Reforma Protestante e Monarquias Compósitas", volume: 2, frente: 2, pinicial: 118, pfinal: 125, prop: 132 },
  { assunto: "A emancipação da América II - Independências na América espanhola", volume: 2, frente: 1, pinicial: 11, pfinal: 18, prop: 25 },
  { assunto: "Religião e monarquia na Época Moderna II - Monarquia francesa, Monarquia inglesa", volume: 2, frente: 2, pinicial: 125, pfinal: 131, prop: 132 },
  { assunto: "A emancipação da América III - Governo Joanino", volume: 2, frente: 1, pinicial: 18, pfinal: 21, prop: 25 },
  { assunto: "A emancipação da América III - Independência do Brasil", volume: 2, frente: 1, pinicial: 21, pfinal: 24, prop: 25 },
  { assunto: "Séc. XVIII - Revolução Industrial e o Iluminismo I - Grã-Bretanha: Revolução Inglesa à Revolução Industrial", volume: 2, frente: 2, pinicial: 150, pfinal: 153, prop: 162 },
  { assunto: "Séc. XVIII - Revolução Industrial e o Iluminismo II - O Iluminismo I", volume: 2, frente: 2, pinicial: 153, pfinal: 157, prop: 162 },
  { assunto: "Primeiro Reinado I - Constituinte, Reações provinciais", volume: 2, frente: 1, pinicial: 44, pfinal: 48, prop: 50 },
  { assunto: "Primeiro Reinado II - Crise do Primeiro Reinado", volume: 2, frente: 1, pinicial: 48, pfinal: 49, prop: 50 },
  { assunto: "Séc. XVIII - Revolução Industrial e o Iluminismo II - O Iluminismo II", volume: 2, frente: 2, pinicial: 157, pfinal: 160, prop: 162 },
  { assunto: "Revoluções Atlânticas I - Contexto, Independência das Treze Colônias", volume: 2, frente: 2, pinicial: 174, pfinal: 177, prop: 198 },
  { assunto: "Período Regencial I - Nova organização, Avanço liberal", volume: 2, frente: 1, pinicial: 60, pfinal: 64, prop: 68 },
  { assunto: "Revoluções Atlânticas II - Revolução Haitiana", volume: 2, frente: 2, pinicial: 177, pfinal: 180, prop: 198 },
  { assunto: "Período Regencial II - Reação conservadora e golpe da maioridade", volume: 2, frente: 1, pinicial: 64, pfinal: 66, prop: 68 },
  { assunto: "Revoluções Atlânticas III - Revolução Francesa I", volume: 2, frente: 2, pinicial: 180, pfinal: 183, prop: 198 },
  { assunto: "Segundo Reinado I - Política interna, economia e sociedade", volume: 2, frente: 1, pinicial: 78, pfinal: 88, prop: 94 },
  { assunto: "Revoluções Atlânticas III - Revolução Francesa II", volume: 2, frente: 2, pinicial: 183, pfinal: 186, prop: 198 },
  { assunto: "Revoluções Atlânticas IV - Era Napoleônica", volume: 2, frente: 2, pinicial: 186, pfinal: 189, prop: 198 },
  { assunto: "Revoluções Atlânticas V - EUA no Séc. XIX I", volume: 2, frente: 2, pinicial: 189, pfinal: 193, prop: 198 },
  { assunto: "Segundo Reinado II - Crise e Proclamação", volume: 2, frente: 1, pinicial: 88, pfinal: 92, prop: 94 },
  { assunto: "Revoluções Atlânticas VI - EUA no Séc. XIX II", volume: 2, frente: 2, pinicial: 193, pfinal: 196, prop: 198 },
  { assunto: "Primeira República I - Aspectos, República da Espada", volume: 3, frente: 1, pinicial: 6, pfinal: 10, prop: 27 },
  { assunto: "O longo século XIX I - Pensamento político e social I", volume: 3, frente: 2, pinicial: 92, pfinal: 95, prop: 117 },
  { assunto: "Primeira República II - Apogeu das oligarquias", volume: 3, frente: 1, pinicial: 10, pfinal: 19, prop: 27 },
  { assunto: "Primeira República III - Crise das oligarquias", volume: 3, frente: 1, pinicial: 19, pfinal: 25, prop: 27 },
  { assunto: "O longo século XIX II - Pensamento político e social II", volume: 3, frente: 2, pinicial: 95, pfinal: 97, prop: 117 },
  { assunto: "O longo século XIX III - Europa entre o Congresso de Viena e a Comuna de Paris", volume: 3, frente: 2, pinicial: 97, pfinal: 100, prop: 117 },
  { assunto: "Era Vargas I - Governo Provisório", volume: 3, frente: 1, pinicial: 52, pfinal: 56, prop: 63 },
  { assunto: "O longo século XIX IV - Unificações da Itália e Alemanha", volume: 3, frente: 2, pinicial: 100, pfinal: 104, prop: 117 },
  { assunto: "Era Vargas II - Governo Constitucional e Estado Novo", volume: 3, frente: 1, pinicial: 56, pfinal: 60, prop: 63 },
  { assunto: "O longo século XIX V - Segunda Revolução Industrial", volume: 3, frente: 2, pinicial: 104, pfinal: 107, prop: 117 },
  { assunto: "O longo século XIX VI - Imperialismo I", volume: 3, frente: 2, pinicial: 107, pfinal: 111, prop: 117 },
  { assunto: "Era Vargas III - Redemocratização", volume: 3, frente: 1, pinicial: 60, pfinal: 60, prop: 63 },
  { assunto: "O longo século XIX VII - Imperialismo II", volume: 3, frente: 2, pinicial: 111, pfinal: 114, prop: 117 },
  { assunto: "A Paz Armada e a Primeira Guerra Mundial I", volume: 3, frente: 2, pinicial: 140, pfinal: 145, prop: 150 },
  { assunto: "Populismo na América Latina", volume: 3, frente: 1, pinicial: 76, pfinal: 80, prop: 83 },
  { assunto: "A Paz Armada e a Primeira Guerra Mundial II", volume: 3, frente: 2, pinicial: 145, pfinal: 148, prop: 150 },
  { assunto: "A Revolução Russa e a União Soviética até 1945 I", volume: 3, frente: 2, pinicial: 158, pfinal: 162, prop: 167 },
  { assunto: "A Revolução Russa e a União Soviética até 1945 II", volume: 3, frente: 2, pinicial: 162, pfinal: 165, prop: 167 },
  { assunto: "República Democrática I - Redemocratização, Governo Dutra", volume: 4, frente: 1, pinicial: 6, pfinal: 9, prop: 18 },
  { assunto: "República Democrática II - Governo Vargas, Governo Juscelino Kubitscheck", volume: 4, frente: 1, pinicial: 9, pfinal: 12, prop: 18 },
  { assunto: "República Democrática III - Jânio Quadros e João Goulart", volume: 4, frente: 1, pinicial: 12, pfinal: 16, prop: 18 },
  { assunto: "As ditaduras no Brasil e na América Latina I - Contexto", volume: 4, frente: 1, pinicial: 32, pfinal: 33, prop: 49 },
  { assunto: "As ditaduras no Brasil e na América Latina II - As ditaduras I", volume: 4, frente: 1, pinicial: 33, pfinal: 39, prop: 49 },
  { assunto: "As ditaduras no Brasil e na América Latina III - As ditaduras II", volume: 4, frente: 1, pinicial: 39, pfinal: 42, prop: 49 },
  { assunto: "As ditaduras no Brasil e na América Latina IV - As ditaduras III", volume: 4, frente: 1, pinicial: 42, pfinal: 47, prop: 49 },
  { assunto: "A Nova República I - Governo José Sarney e Fernando Collor de Melo", volume: 4, frente: 1, pinicial: 68, pfinal: 71, prop: 84 },
  { assunto: "A Nova República II - Governo Itamar Franco e Governo Fernando Henrique Cardoso", volume: 4, frente: 1, pinicial: 71, pfinal: 74, prop: 84 },
  { assunto: "A Nova República III - Governo Lula, Governo Dilma", volume: 4, frente: 1, pinicial: 74, pfinal: 76, prop: 84 },
  { assunto: "A Nova República IV - Governo Temer, Governo Bolsonaro", volume: 4, frente: 1, pinicial: 76, pfinal: 77, prop: 84 },
  { assunto: "Período Entreguerras I - Crise 1929", volume: 4, frente: 2, pinicial: 90, pfinal: 93, prop: 103 },
  { assunto: "Período Entreguerras II - Fascismo", volume: 4, frente: 2, pinicial: 93, pfinal: 96, prop: 103 },
  { assunto: "Período Entreguerras III - Nazismo na Alemanha e Guerra Civil Espanhola", volume: 4, frente: 2, pinicial: 96, pfinal: 100, prop: 103 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo I - Segunda Guerra I", volume: 4, frente: 2, pinicial: 118, pfinal: 120, prop: 142 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo II - Segunda Guerra II", volume: 4, frente: 2, pinicial: 120, pfinal: 122, prop: 142 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo III - Guerra Fria I", volume: 4, frente: 2, pinicial: 122, pfinal: 126, prop: 142 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo IV - Guerra Fria II", volume: 4, frente: 2, pinicial: 126, pfinal: 130, prop: 142 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo V - Guerra Fria III", volume: 4, frente: 2, pinicial: 130, pfinal: 134, prop: 142 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo VI - Guerra Fria IV", volume: 4, frente: 2, pinicial: 134, pfinal: 137, prop: 142 },
  { assunto: "Segunda Guerra e Mundo Contemporâneo VII - Fim da Guerra Fria e Nova Ordem Mundial", volume: 4, frente: 2, pinicial: 137, pfinal: 140, prop: 142 }
              ]
            }*/
           
        ]);

        /*await Cronograma.create({
            segunda: ["Biologia", "Química", "História"],
            terça: ["Geografia", "Português", "Física"],
            quarta: ["Filosofia", "Biologia", "Matemática"],
            quinta: ["Física", "Sociologia", "Matemática"],
            sexta: ["Português", "Matemática", "Geografia"],
            sábado: ["Química", "História", "Biologia", "Matemática"],
            domingo: ["Matemática"]
        });*/

        console.log('✅ Dados populados com sucesso!');
    } catch (error) {
        console.error('❌ Erro ao popular dados:', error);
    } finally {
        await mongoose.connection.close();
        console.log('🔌 Conexão encerrada');
    }
}

populateDatabase();